### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute

### ISSUE THREAD

**Issue by hhhoushiyu** [RenYurui/StructureFlow#12]
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    main('train')
  File "/project/StructureFlow/main.py", line 31, in main
    model.train()
  File "/project/StructureFlow/src/structure_flow.py", line 77, in train
    logs = self.flow_model.update_flow(inputs, smooth_stage_1.detach(), gts, maps, self.flow_model.use_correction_loss, self.flow_model.use_vgg_loss)
  File "/project/StructureFlow/src/models.py", line 169, in update_flow
    self.config.FLOW_CORRECTNESS if use_correction_loss else 0
  File "/project/StructureFlow/src/loss.py", line 137, in __call__
    correction = torch.bmm(input_norm, gt_norm)                       #[b N2 N2]
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCBlas.cu:450

Ubuntu 16.04
GPU NVIDIA TITAN RTX
CUDA 9.0 pytorch 1.1.0 python 3.6.9

anybody can help?Thank you very much.

**Comment by RenYurui** [comment]
Have you solved this problem? 
Is everything ok when you run other code with your environment?
I think it may not be caused by our code.

**Comment by hhhoushiyu** [comment]
> Have you solved this problem?
> Is everything ok when you run other code with your environment?
> I think it may not be caused by our code.
Thank you for your reply.I think this is due to the fact that my graphics card is TITAN RTX, which has some mismatches with cuda9.0

**Comment by hhhoushiyu** [comment]
> Have you solved this problem?
> Is everything ok when you run other code with your environment?
> I think it may not be caused by our code.

Thank you for your reply.I think this is due to the fact that my graphics card is TITAN RTX, which has some mismatches with cuda9.0

**Comment by zhangbaijin** [comment]
excuse me, i'm in trouble . I make a paris-street.txt .It contains the path of the picture, like ```
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.843916_2.349357_90_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.853997_2.367366_90_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.860426_2.350230_270_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.859209_2.359542_270_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.859447_2.368619_270_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.854558_2.333406_90_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.849259_2.337861_270_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.848829_2.347725_90_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.861772_2.367048_90_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.852498_2.363940_270_-004.JPG
/home/zxf/桌面/StructureFlow-master/dataset/paris_street/48.843261_2.336452_90_-004.JPG
```
and i download the 'code'and put it into matlab folder,so I run generate_structure_images.m('/home/zxf/桌面/StructureFlow-master/paris-street.txt','/home/zxf/桌面/StructureFlow-master/Output')...But it doesn't generate any images in Output floder....I I don't know what the problem is...Thanks for your time ..Best wishes

**Comment by dldms1345** [comment]
> > Have you solved this problem?
> > Is everything ok when you run other code with your environment?
> > I think it may not be caused by our code.
> 
> Thank you for your reply.I think this is due to the fact that my graphics card is TITAN RTX, which has some mismatches with cuda9.0

I have a same error. Can you tell me how to fix it?
I would be grateful if you let me know in what environment you did it.
