### ISSUE TITLE
the metric computation

### ISSUE THREAD

**Issue by weizequan** [RenYurui/StructureFlow#14]
Hi Yurui,

   In your scripts/metrics.py, i guess the "inputs" in "__call__(self, inputs, gts)" (used for computing the 'ssim', 'psnr', 'l1', etc) are the direct outputs of your network? not the merged version, i.e., outputs * masks + inputs * (1 - masks) [just change the hole regions]? Thanks a lot.

**Comment by RenYurui** [comment]
The input image is the merged results [ input = (outputs * maps) + (gts * (1 - maps)) ]
see Function test()  in structure_flow.py for detail.
