### ISSUE TITLE
CUDA problem

### ISSUE THREAD

**Issue by zhangbaijin** [RenYurui/StructureFlow#15]
hi, my problem is `RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/pip-req-build-ocx5vxk7/aten/src/THC/THCGeneral.cpp:50
`
GTX1080Ti and my cuda is 10 ,is it my cuda problem? thanks for your time!

**Comment by RenYurui** [comment]
We test the code using CUDA 9.0.
Your error means that no CUDA device is detected. This may not cause by our code. Therefore, you may need to first check your environment. Can you run other code using this environment?

**Comment by 893205894** [comment]
hi，when i 'Build Gaussian Sampling CUDA package', it said `fatal error: c10/cuda/impl/cuda_cmake_macros.h: No such file or directory
 #include <c10/cuda/impl/cuda_cmake_macros.h>` ,so how can i solve this ?thanks for your reply.

**Comment by 893205894** [comment]
uh，i solve the problem above. my pytorch version was 1.2, and it was ok after i made it to 1.0.

**Comment by zhangbaijin** [comment]
OK，Best wishes.

**Comment by FindTheAnswer** [comment]
> hi, my problem is `RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/pip-req-build-ocx5vxk7/aten/src/THC/THCGeneral.cpp:50 `
> GTX1080Ti and my cuda is 10 ,is it my cuda problem? thanks for your time!

Hello, I meet the same question.Have you solved this problem?

**Comment by jiunyen-ching** [comment]
@FindTheAnswer in your model_config.yaml file, what is the GPU ID? I think I had the same error message because I didn't set the GPU ID properly.
