### ISSUE TITLE
list question

### ISSUE THREAD

**Issue by zhangbaijin** [RenYurui/StructureFlow#16]
when i run` generate_structure_images("path to Places2 list file", "path to output folder");`what is  place2 list file ??

**Comment by zhangbaijin** [comment]
excuse me, i'm in trouble . I make a paris-street.txt .It contains the path of the picture, like 
/home/StructureFlow-master/dataset/paris_street/48.843916_2.349357_90_-004.JPG
and i download the 'code'and put it into matlab folder,so I run `generate_structure_images.m('/home/StructureFlow-master/paris-street.txt,'/home/StructureFlow-master/Output')` and it doesn't generate any  images in output floder ....Thanks for time. Best wishes.

**Comment by 1559145087** [comment]
it seem like that you don't need a txt file, just let "path to Places2 list file" link to dataset dir. I run this code by generate_structure_images('F:\celeba-512', 'F:\celeba_512_stru')
