### ISSUE TITLE
result is not good

### ISSUE THREAD

**Issue by zhangbaijin** [RenYurui/StructureFlow#19]
Excuse me ,Whether should i train model 1 first,and then 2,last 3?? I train it directly with Scenery dataset,but the results not so good..I notice that there is no latest_net_s_gen.pth in my floder..

**Comment by RenYurui** [comment]
You need to train model1 and model2 before you train model3. Model1 and model2 can be trained simultaneously, cause they do not need the results of each other. Model3 fine-tunes the texture generation network using the reconstructed results of model1.  

You can also use the provided pre-trained weights.
