### ISSUE TITLE
Multi gpu issue

### ISSUE THREAD

**Issue by kyoungkookkang** [RenYurui/StructureFlow#21]
Hello Sorry to bother you.

I have one question. 

can this model be trained using multi gpu? is there anything to change the code to use multi gpus?

**Comment by RenYurui** [comment]
You need to change the source code to train this model using Multi-GPU
You can use the torch.nn.DataParallel function such as:
```python
  self.net = torch.nn.DataParallel(self.net, device_ids=self.gpu_ids)                
```
Check https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html for more details.

**Comment by kyoungkookkang** [comment]
I got it Thank you
