### ISSUE TITLE
Question abount the input structure during test

### ISSUE THREAD

**Issue by cmyyy** [RenYurui/StructureFlow#27]
@RenYurui , hello.
Is the input structure obtained according to the equation S_in = S_gt ◦ (1 − M) during test?

**Comment by RenYurui** [comment]
Yes.
The input structure images are obtained by the equation.

**Comment by cmyyy** [comment]
And S_gt is obtained from I_gt. In practical terms, since I_gt is known, do we need to inpaint ?

**Comment by cmyyy** [comment]
Could you provide "latest_net_f_dis.pth" and "latest_net_s_dis.pth"? It seems we need these to run test.py successfully.THX!!

**Comment by RenYurui** [comment]
In practice, we can directly smooth the S_in image using the RTV method. 
However, some modifications are needed. We will provide an update to deal with this situation.

**Comment by RenYurui** [comment]
The 'tsmooth.m' is updated to smooth the masked input image I_in.
Use the following code
``` matlab
S = t_smooth(I_in, 0.015, 3, 0.001, 3, mask);
```
where I_in = I_gt * (1-mask)
