### ISSUE TITLE
Exporting models issue

### ISSUE THREAD

**Issue by zosel260** [RenYurui/StructureFlow#28]
Hello,
I tried to export your models to .onnx or .pt. for other platform (Matlab or C++) to use them in Matlab codes.
The first model(StructureGen ) is successfully converted to .onnx and .pt. 
The second one(FlowGen), however, can not be converted because of the customized layer 'Resample2DFunction' .
Do you have any advice for this problem?
Thanks ahead.
-----------------------------------------------------------------------
1) export the model to the .pt  
    def flow_forward(self, inputs, stage_1, maps):
      outputs, flow = self.f_gen(torch.cat((inputs, stage_1, maps),dim=1))
      input_cat = torch.cat((inputs, stage_1, maps), dim=1)
      traced_script_module = torch.jit.trace(self.f_gen, input_cat)
      outputs2, flow2 = traced_script_module(input_cat)
      traced_script_module.save("structure_inpainting_model.pt")
 ==> error reports:
 ....
  File "/home/yskim/yky/inpainting/StructureFlow-master/src/models.py", line 123, in flow_forward
    traced_script_module.save("structure_inpainting_model.pt")
  File "/home/yskim/anaconda3/envs/edgeconnect1/lib/python3.6/site-packages/torch/jit/__init__.py", line 1626, in save
    return self._c.save(*args, **kwargs)
RuntimeError: 
Could not export Python function call 'Resample2dFunction'. Remove calls to Python functions before export. Did you forget add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
/home/yskim/yky/inpainting/StructureFlow-master/src/resample2d.py(65): forward
------------------------------------------------------------------------
2) export the  model to the .onnx
 def flow_forward(self, inputs, stage_1, maps):
    outputs, flow = self.f_gen(torch.cat((inputs, stage_1, maps),dim=1))
   torch.onnx.export(self.f_gen,  # model being run
                          input_cat,  # model input (or a tuple for multiple inputs)
                          "structure_inpainting_model.onnx",  # where to save the model (can be a file or file-like object)
                          export_params=True,  # store the trained parameter weights inside the model file
                          opset_version=11,  # the ONNX version to export the model to
                          do_constant_folding=True,  # whether to execute constant folding for optimization
                          input_names=['input'],  # the model's input names
                          output_names=['output'],  # the model's output names
                          operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
   
==>error reports:
...
 File "/home/yskim/anaconda3/envs/edgeconnect1/lib/python3.6/site-packages/torch/onnx/utils.py", line 428, in _export
    operator_export_type, strip_doc_string, val_keep_init_as_ip)
RuntimeError: ONNX export failed: Couldn't export Python operator Resample2dFunction

Defined at:
/home/yskim/yky/inpainting/StructureFlow-master/src/resample2d.py(65): forward

**Comment by zosel260** [comment]
For the "1.export the model to the .pt" case,  I also tried @script_method annotation on the 'Resample2DFunction' to follow the direction on error reports,  but  I got these errors:
  File "/home/yskim/yky/inpainting/StructureFlow-master/src/resample2d.py", line 65, in forward
    return Resample2dFunction.apply(input1_c, input2, self.kernel_size, self.dilation)
TypeError: 'ScriptMethodStub' object is not callable

**Comment by RenYurui** [comment]
Hi, we have not tried to run this code using Matlab. Our model contains custom PyTorch modules, which may be the reason for the failure.
