### ISSUE TITLE
Segmentation Fault when train model=2

### ISSUE THREAD

**Issue by ReSpike** [RenYurui/StructureFlow#8]
I installed the new layer follow README and try to train the inpaint model. The structure model was training perfectly, but I got Segmentation Fault in the 2nd inpaint model. The version of my pytorch is 1.0.1. 
Are there anybody else meet the same problem?
Would you please to help me to check it?

**Comment by RenYurui** [comment]
Could you please tell me your gup and cuda vision? 
Is there any problem when you build the Gaussian sampling layer?
