### ISSUE TITLE
question about training masks

### ISSUE THREAD

**Issue by cmyyy** [RenYurui/StructureFlow#9]
Hello, @RenYurui , good work.
Were the training masks augmented from test set of irregular mask dataset from **partial conv** like **edge-connect** did ?

**Comment by RenYurui** [comment]
Yes, the test set of the irregular mask dataset is used.

**Comment by cmyyy** [comment]
@RenYurui , hello.
I noticed that you use the direct output of model to calculate losses, but in **CA** , they merge the ground truth outside the hole region and the generated content in the hole region to do this. In your opinion, which way is better?

**Comment by cmyyy** [comment]
When you train model on places2, were the training image resized to 256*256 from original size or random cropped? And what about the test image?
Thx.

**Comment by RenYurui** [comment]
Q1: We resize the image to 256*256.
Q2: We randomly select masks for the test images. Each test image has 6 masks with different mask ratios (0-10%, 10-20% ... 50-60%). The evaluation results are obtained according to the 60000 output images.

**Comment by cmyyy** [comment]
Thanks!

**Comment by zhangbaijin** [comment]
excuse me, i'm in trouble . I make a paris-street.txt .It contains the path of the picture, like
/home/StructureFlow-master/dataset/paris_street/48.843916_2.349357_90_-004.JPG
and i download the 'code'and put it into matlab folder,so I run generate_structure_images.m('/home/StructureFlow-master/paris-street.txt,'/home/StructureFlow-master/Output') and it doesn't generate any images in output floder ....Thanks for your time. Best wishes.

**Comment by jiunyen-ching** [comment]
@zhangbaijin The first input is simply the path to the image folder containing the images i.e.
`generate_structure_images('/path/to/image/folder','/path/to/output/folder')`. 

In your case, it would be
`generate_structure_images('/home/StructureFlow-master/dataset/paris_street','/home/StructureFlow-master/Output')`
